# Generated by Django 5.1.5 on 2026-08-22 20:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], max_length=3)),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('PURCHASE_INSTALLMENT', 'Cuota de compra')], default='MANUAL', max_length=25)),
                ('installment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('installment_total', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], default='USD', max_length=3)),
                ('estimated_amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='CUIT')),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('concept', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], default='USD', max_length=3)),
                ('fx_ars_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('installment_count', models.PositiveIntegerField(default=0)),
                ('first_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('INVESTOR', 'Inversor')], default='INVESTOR', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('work_type', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('DONE', 'Realizado'), ('INVOICED', 'Facturado'), ('COLLECTED', 'Cobrado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], default='ARS', max_length=3)),
                ('fx_ars_usd', models.DecimalField(decimal_places=4, max_digits=15)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('SETTLED', 'Cobrada')], default='OPEN', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.client')),
                ('jobs', models.ManyToManyField(related_name='invoices', to='core.job')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('concept', models.CharField(max_length=255)),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], default='ARS', max_length=3)),
                ('fx_ars_usd', models.DecimalField(decimal_places=4, max_digits=15)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_by', models.CharField(choices=[('CASH', 'Caja'), ('INVESTOR', 'Inversor')], default='CASH', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.account')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid', to='core.investor')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.job')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], default='ARS', max_length=3)),
                ('fx_ars_usd', models.DecimalField(decimal_places=4, max_digits=15)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_loss_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CapitalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('CONTRIBUTION', 'Aporte directo'), ('RESCUE', 'Rescate'), ('JOB_DISTRIBUTION', 'Reparto de cobro')], max_length=20)),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], default='ARS', max_length=3)),
                ('fx_ars_usd', models.DecimalField(decimal_places=4, max_digits=15)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('work_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('shareholder_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_events', to='core.account')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_events', to='core.investor')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capital_events', to='core.payment')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.purchase'),
        ),
    ]
