# Generated by Django 5.1.5 on 2026-02-20 23:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('ars_per_usd', models.DecimalField(decimal_places=4, max_digits=15)),
                ('source', models.CharField(default='manual', max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=30, unique=True)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('work_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PLANNED', 'Planificado'), ('BILLED', 'Facturado'), ('COLLECTED', 'Cobrado'), ('CANCELLED', 'Cancelado')], default='PLANNED', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('concept', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_currency', models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('concept', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], default='USD', max_length=3)),
                ('fx_ars_usd', models.DecimalField(decimal_places=4, max_digits=15)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_by', models.CharField(choices=[('INVESTOR', 'Inversor'), ('CASH', 'Caja')], default='INVESTOR', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('payer_investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.investor')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], max_length=3)),
                ('category', models.CharField(choices=[('JOB_COLLECTION', 'Cobro trabajo'), ('REINVESTMENT', 'Reinversión'), ('EXPENSE', 'Gasto'), ('PURCHASE_PAYMENT', 'Pago compra'), ('ADJUSTMENT', 'Ajuste')], max_length=20)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.investor')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CapitalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('EXPENSE', 'Gasto pagado'), ('REINVESTMENT', 'Reinversión'), ('DIRECT', 'Aporte directo')], max_length=20)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_contributions', to='core.investor')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('amount_ars', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('fx_ars_usd', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=15)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COLLECTED', 'Cobrado')], default='COLLECTED', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.job')),
            ],
            options={
                'ordering': ['-collection_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FIELD_TEAM', 'Equipo de campo'), ('SHAREHOLDER', 'Accionista'), ('REINVESTMENT', 'Reinversión')], max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='core.jobcollection')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.investor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], default='USD', max_length=3)),
                ('estimated_amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='core.purchase')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reinvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reinvestments', to='core.investor')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
    ]
