# Generated by Django 5.1.5 on 2026-02-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='alias',
        ),
    ]
