# Generated by Django 5.1.5 on 2026-02-21 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_investor_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.paymentobligation'),
        ),
        migrations.AddField(
            model_name='expense',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.purchase'),
        ),
    ]
