# Generated by Django 5.1.5 on 2026-02-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expense_payment_obligation_expense_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='fx_ars_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_amount_ars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
