# Generated by Django 5.1.5 on 2026-02-26 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_purchase_fx_ars_usd_purchase_total_amount_ars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentobligation',
            name='concept',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentobligation',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentobligation',
            name='installment_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentobligation',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PURCHASE_INSTALLMENT', 'Cuota de compra')], default='MANUAL', max_length=25),
        ),
        migrations.AddField(
            model_name='purchase',
            name='first_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='installment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentobligation',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='core.purchase'),
        ),
        migrations.AddConstraint(
            model_name='paymentobligation',
            constraint=models.CheckConstraint(condition=models.Q(('source', 'MANUAL'), ('purchase__isnull', False), _connector='OR'), name='obligation_purchase_required_for_installment'),
        ),
    ]
