# Generated by Django 5.1.5 on 2026-02-27 02:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paymentobligation_concept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcontribution',
            name='cash_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='core.cashmovement'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movement', to='core.expense'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='job_distribution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movement', to='core.jobdistribution'),
        ),
        migrations.AddField(
            model_name='jobdistribution',
            name='reinvest_to_cash_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='capitalcontribution',
            name='kind',
            field=models.CharField(choices=[('EXPENSE', 'Gasto pagado'), ('REINVESTMENT', 'Reinversión'), ('DIRECT', 'Aporte directo'), ('WITHDRAWAL', 'Rescate de capital')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='category',
            field=models.CharField(choices=[('JOB_COLLECTION', 'Cobro trabajo'), ('PROFIT_REINVESTMENT', 'Reinversión de utilidad'), ('CAPITAL_CONTRIBUTION', 'Aporte de capital'), ('CAPITAL_RESCUE', 'Rescate de capital'), ('INVESTOR_WITHDRAWAL', 'Retiro de inversor'), ('EXPENSE', 'Gasto'), ('PURCHASE_PAYMENT', 'Pago compra'), ('ADJUSTMENT', 'Ajuste')], max_length=20),
        ),
    ]
