# Generated by Django 5.1.5 on 2026-02-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_migrate_reinvestments_to_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcollection',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcollection',
            name='settlement_status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('CLOSED', 'Cerrada')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='category',
            field=models.CharField(choices=[('JOB_COLLECTION', 'Cobro trabajo'), ('FIELD_TEAM_PAYOUT', 'Pago equipo campo'), ('PROFIT_REINVESTMENT', 'Reinversión de utilidad'), ('CAPITAL_CONTRIBUTION', 'Aporte de capital'), ('CAPITAL_RESCUE', 'Rescate de capital'), ('INVESTOR_WITHDRAWAL', 'Retiro de inversor'), ('EXPENSE', 'Gasto'), ('PURCHASE_PAYMENT', 'Pago compra'), ('ADJUSTMENT', 'Ajuste')], max_length=20),
        ),
    ]
