# Generated by Django 5.1.5 on 2026-02-28 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_jobcollection_settled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.job'),
        ),
    ]
