# Generated by Django 5.1.5 on 2026-02-28 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_job_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcollection',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='grouped_collections', to='core.job'),
        ),
        migrations.AlterField(
            model_name='jobcollection',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='core.job'),
        ),
    ]
