# Generated by Codex on 2026-02-28

from django.db import migrations


def backfill_jobs(apps, schema_editor):
    JobCollection = apps.get_model("core", "JobCollection")
    for collection in JobCollection.objects.exclude(job_id__isnull=True).iterator():
        collection.jobs.add(collection.job_id)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_jobcollection_jobs_alter_jobcollection_job"),
    ]

    operations = [
        migrations.RunPython(backfill_jobs, migrations.RunPython.noop),
    ]

