# Generated by Codex on 2026-02-28

from django.db import migrations, models


def migrate_pending_to_billed(apps, schema_editor):
    JobCollection = apps.get_model("core", "JobCollection")
    JobCollection.objects.filter(status="PENDING").update(status="BILLED")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcollection",
            name="status",
            field=models.CharField(
                choices=[("BILLED", "Facturado"), ("COLLECTED", "Cobrado")],
                default="BILLED",
                max_length=10,
            ),
        ),
        migrations.RunPython(migrate_pending_to_billed, migrations.RunPython.noop),
    ]

