# Generated by Codex on 2026-02-28

from django.db import migrations, models


def migrate_job_statuses(apps, schema_editor):
    Job = apps.get_model("core", "Job")
    Job.objects.filter(status="PLANNED").update(status="PENDING")
    Job.objects.filter(status="BILLED").update(status="DONE")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_jobcollection_status_billed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("DONE", "Realizado"),
                    ("INVOICED", "Facturado"),
                    ("COLLECTED", "Cobrado"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.RunPython(migrate_job_statuses, migrations.RunPython.noop),
    ]

