# Generated by Codex on 2026-02-28

from decimal import Decimal
from django.db import migrations, models


def backfill_collected_amount(apps, schema_editor):
    JobCollection = apps.get_model("core", "JobCollection")
    for col in JobCollection.objects.filter(status="COLLECTED", collected_amount_usd__isnull=True).iterator():
        col.collected_amount_usd = col.amount_usd
        col.tax_loss_usd = Decimal("0")
        col.save(update_fields=["collected_amount_usd", "tax_loss_usd"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_job_status_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcollection",
            name="collected_amount_usd",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="jobcollection",
            name="tax_loss_usd",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=15),
        ),
        migrations.RunPython(backfill_collected_amount, migrations.RunPython.noop),
    ]

