# Generated by Codex on 2026-02-28

from django.db import migrations, models


def backfill_collected_original(apps, schema_editor):
    JobCollection = apps.get_model("core", "JobCollection")
    for col in JobCollection.objects.filter(status="COLLECTED").iterator():
        if not col.collected_currency:
            col.collected_currency = "USD"
        if col.collected_amount_original is None:
            col.collected_amount_original = col.collected_amount_usd or col.amount_usd
        col.save(update_fields=["collected_currency", "collected_amount_original"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_jobcollection_collected_amount_tax_loss"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcollection",
            name="collected_amount_original",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="jobcollection",
            name="collected_currency",
            field=models.CharField(blank=True, choices=[("USD", "USD"), ("ARS", "ARS")], max_length=3, null=True),
        ),
        migrations.RunPython(backfill_collected_original, migrations.RunPython.noop),
    ]

