# Generated by Codex on 2026-02-28

from django.db import migrations, models


def backfill_converted_and_fx(apps, schema_editor):
    JobCollection = apps.get_model("core", "JobCollection")
    for col in JobCollection.objects.filter(status="COLLECTED").iterator():
        if col.collected_currency == "USD":
            col.converted_to_usd = True
            col.collected_fx_ars_usd = None
        else:
            col.converted_to_usd = bool(col.collected_amount_usd)
            if col.collected_fx_ars_usd is None:
                col.collected_fx_ars_usd = col.fx_ars_usd
        col.save(update_fields=["converted_to_usd", "collected_fx_ars_usd"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_jobcollection_collected_original_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcollection",
            name="collected_fx_ars_usd",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="jobcollection",
            name="converted_to_usd",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_converted_and_fx, migrations.RunPython.noop),
    ]

